# -*- coding: utf-8 -*-
"""Hostel_food_Review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18-2YmAyFaqnszZqyKuKdmvdJKe7CSUf-
"""

# Importing essential libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the dataset from uploaded file
df = pd.read_excel('/content/Hostel_Food_Review.xlsx')  # Path in Colab
print("Dataset Loaded Successfully")
df.head()

print("Null Values in Each Column:\n", df.isnull().sum())

# Top Rated Dishes
top_dishes = df.sort_values(by='Rating(1-5)', ascending=False)
print("Top Rated Dishes:\n")
print(top_dishes[['Food_item', 'Rating(1-5)']].head(10).to_string(index=False))

# Least Rated Dishes
least_dishes = df.sort_values(by='Rating(1-5)', ascending=True)
print("\nLeast Rated Dishes:\n")
print(least_dishes[['Food_item', 'Rating(1-5)']].head(10).to_string(index=False))

df['Meal_Type'] = df['Meal_Type'].str.strip().str.lower()

meal_avg_rating = df.groupby('Meal_Type')['Rating(1-5)'].mean().reset_index().sort_values(by='Rating(1-5)', ascending=False)
print(meal_avg_rating.to_string(index=False))

# Bar Plot for Meal Type Ratings
plt.figure(figsize=(8,6))
sns.barplot(x='Meal_Type', y='Rating(1-5)', data=meal_avg_rating, palette='viridis')
plt.title('Average Rating of Each Meal Type')
plt.xlabel('Meal Type')
plt.ylabel('Average Rating')
plt.show()

# Counting Dishes per Meal Type
meal_type_counts = df['Meal_Type'].value_counts().reset_index()
meal_type_counts.columns = ['Meal_Type', 'Dish_Count']
print(meal_type_counts)

# Bar Plot for Number of Dishes in each Meal Type
plt.figure(figsize=(8,6))
sns.barplot(x='Meal_Type', y='Dish_Count', data=meal_type_counts, palette='Set2')
plt.title('Number of Dishes per Meal Type')
plt.xlabel('Meal Type')
plt.ylabel('Number of Dishes')
plt.show()

import matplotlib.pyplot as plt
# Rating Distribution
rating_counts = df['Rating(1-5)'].value_counts().sort_index()
# Plot
plt.figure(figsize=(8,5))
rating_counts.plot(kind='bar', color='skyblue', edgecolor='black')
plt.title('Rating Distribution of Hostel Food', fontsize=14)
plt.xlabel('Ratings', fontsize=12)
plt.ylabel('Number of Dishes', fontsize=12)
plt.xticks(rotation=0)
plt.show()